# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-15 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courseDesc',
            field=models.CharField(default='null', max_length=500),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_logo',
            field=models.FileField(upload_to=''),
        ),
    ]
