# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-15 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20180215_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseDesc',
            field=models.CharField(max_length=500),
        ),
    ]
