# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-20 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20180215_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='document_upload',
        ),
    ]
