# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-20 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_lesson_document_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='document_upload',
            field=models.FileField(default='null', upload_to=''),
        ),
    ]
